// <auto-generated />
using E_commerce_2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_commerce_2.Migrations
{
    [DbContext(typeof(TheMarketDBContext))]
    [Migration("20230828201338_odai")]
    partial class odai
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_commerce_2.Models.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "111111111111111111111111",
                            Logo = "https://faststorestorage.blob.core.windows.net/images/R.jpg",
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 2,
                            Description = "22222222222222222",
                            Logo = "https://faststorestorage.blob.core.windows.net/images/R.jpg",
                            Name = "Clothes"
                        });
                });

            modelBuilder.Entity("E_commerce_2.Models.CategoriesProduct", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CategoriesProducts");

                    b.HasData(
                        new
                        {
                            CategoriesId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            CategoriesId = 1,
                            ProductId = 2
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductId = 3
                        });
                });

            modelBuilder.Entity("E_commerce_2.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "1111111111111111",
                            ImageURL = "https://faststorestorage.blob.core.windows.net/images/R.jpg",
                            Name = "Name1",
                            Price = 5m
                        },
                        new
                        {
                            Id = 2,
                            Description = "2222222222222222",
                            ImageURL = "https://faststorestorage.blob.core.windows.net/images/R.jpg",
                            Name = "Name2",
                            Price = 10m
                        },
                        new
                        {
                            Id = 3,
                            Description = "3333333333333333333",
                            ImageURL = "https://faststorestorage.blob.core.windows.net/images/R.jpg",
                            Name = "Name3 ",
                            Price = 15m
                        });
                });

            modelBuilder.Entity("E_commerce_2.Models.CategoriesProduct", b =>
                {
                    b.HasOne("E_commerce_2.Models.Categories", "categories")
                        .WithMany("categoriesProducts")
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_commerce_2.Models.Product", "product")
                        .WithMany("categoriesProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categories");

                    b.Navigation("product");
                });

            modelBuilder.Entity("E_commerce_2.Models.Categories", b =>
                {
                    b.Navigation("categoriesProducts");
                });

            modelBuilder.Entity("E_commerce_2.Models.Product", b =>
                {
                    b.Navigation("categoriesProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
